// Etapas do pipeline (18 colunas — SPEC-001 §6.3 / §7.1)
export enum Stage {
  SINAIS_MERCADO = 'SINAIS_MERCADO',
  IDEIAS_BRUTAS = 'IDEIAS_BRUTAS',
  IDEIAS_VALIDADAS = 'IDEIAS_VALIDADAS',
  ANGULO_DEFINIDO = 'ANGULO_DEFINIDO',
  HOOKS_EM_TESTE = 'HOOKS_EM_TESTE',
  ROTEIRO = 'ROTEIRO',
  DIRECAO_CRIATIVA = 'DIRECAO_CRIATIVA',
  PRONTO_PARA_GRAVAR = 'PRONTO_PARA_GRAVAR',
  GRAVADO = 'GRAVADO',
  EM_EDICAO = 'EM_EDICAO',
  REVISAO_RETENCAO = 'REVISAO_RETENCAO',
  COPY_LEGENDA_CTA = 'COPY_LEGENDA_CTA',
  AGENDADO = 'AGENDADO',
  PUBLICADO = 'PUBLICADO',
  EM_DISTRIBUICAO = 'EM_DISTRIBUICAO',
  ANALISE = 'ANALISE',
  ESCALAR_RECICLAR = 'ESCALAR_RECICLAR',
  ARQUIVADO = 'ARQUIVADO',
}

export const STAGE_ORDER: Stage[] = [
  Stage.SINAIS_MERCADO,
  Stage.IDEIAS_BRUTAS,
  Stage.IDEIAS_VALIDADAS,
  Stage.ANGULO_DEFINIDO,
  Stage.HOOKS_EM_TESTE,
  Stage.ROTEIRO,
  Stage.DIRECAO_CRIATIVA,
  Stage.PRONTO_PARA_GRAVAR,
  Stage.GRAVADO,
  Stage.EM_EDICAO,
  Stage.REVISAO_RETENCAO,
  Stage.COPY_LEGENDA_CTA,
  Stage.AGENDADO,
  Stage.PUBLICADO,
  Stage.EM_DISTRIBUICAO,
  Stage.ANALISE,
  Stage.ESCALAR_RECICLAR,
  Stage.ARQUIVADO,
];

// Pilares de conteúdo (PRD §8)
export enum Pillar {
  DOR_DONO_AGENCIA = 'DOR_DONO_AGENCIA',
  QUEBRA_CRENCA = 'QUEBRA_CRENCA',
  OPORTUNIDADE_TICKET = 'OPORTUNIDADE_TICKET',
  PRODUTO_MECANISMO = 'PRODUTO_MECANISMO',
  PROVA_BASTIDORES = 'PROVA_BASTIDORES',
  OBJECOES = 'OBJECOES',
  AUTORIDADE = 'AUTORIDADE',
}

export enum AwarenessLevel {
  PROBLEMA = 'PROBLEMA',
  NOVA_PERSPECTIVA = 'NOVA_PERSPECTIVA',
  IDENTIFICACAO = 'IDENTIFICACAO',
  INTENCAO = 'INTENCAO',
}

export enum ContentClass {
  VIRAL = 'VIRAL',
  AUTORIDADE = 'AUTORIDADE',
  VENDEDOR = 'VENDEDOR',
  FRACO = 'FRACO',
}

export enum SignalSource {
  WHATSAPP_LEAD = 'WHATSAPP_LEAD',
  OBJECAO_CALL = 'OBJECAO_CALL',
  COMENTARIO_INSTAGRAM = 'COMENTARIO_INSTAGRAM',
  ANUNCIO_CONCORRENTE = 'ANUNCIO_CONCORRENTE',
  PRINT_CONVERSA = 'PRINT_CONVERSA',
  RECLAMACAO_LEADS_RUINS = 'RECLAMACAO_LEADS_RUINS',
}

export enum AngleType {
  DOR = 'DOR',
  CULPA_TRANSFERIDA = 'CULPA_TRANSFERIDA',
  OPORTUNIDADE = 'OPORTUNIDADE',
  MEDO = 'MEDO',
  AUTORIDADE = 'AUTORIDADE',
}

export enum CreativeFormat {
  PESSOA_FALANDO = 'PESSOA_FALANDO',
  PRINTS_PROCESSO = 'PRINTS_PROCESSO',
  POV_DONO_AGENCIA = 'POV_DONO_AGENCIA',
  ANTES_DEPOIS = 'ANTES_DEPOIS',
  CHECKLIST = 'CHECKLIST',
  STORYTELLING = 'STORYTELLING',
  COMPARATIVO = 'COMPARATIVO',
  TREND_ADAPTADA = 'TREND_ADAPTADA',
  SIMULACAO_CONVERSA = 'SIMULACAO_CONVERSA',
  DEMONSTRACAO_PRODUTO = 'DEMONSTRACAO_PRODUTO',
}

export enum DerivedAssetType {
  CARROSSEL = 'CARROSSEL',
  STORY = 'STORY',
  ANUNCIO = 'ANUNCIO',
  EMAIL = 'EMAIL',
  CORTE_SHORTS = 'CORTE_SHORTS',
  POST_LINKEDIN = 'POST_LINKEDIN',
  SCRIPT_SDR = 'SCRIPT_SDR',
  HOOK_NOVO = 'HOOK_NOVO',
}

export enum Role {
  ADMIN = 'ADMIN',
  GESTOR = 'GESTOR',
  ESTRATEGISTA = 'ESTRATEGISTA',
  ROTEIRISTA = 'ROTEIRISTA',
  GRAVACAO = 'GRAVACAO',
  EDITOR = 'EDITOR',
  REVISOR_RETENCAO = 'REVISOR_RETENCAO',
}

export enum HookStatus {
  EM_TESTE = 'EM_TESTE',
  ESCOLHIDO = 'ESCOLHIDO',
  DESCARTADO = 'DESCARTADO',
}

export enum ValidationVerdict {
  DESCARTAR = 'DESCARTAR',
  MELHORAR_ANGULO = 'MELHORAR_ANGULO',
  SEGUIR_ROTEIRO = 'SEGUIR_ROTEIRO',
}

export enum AIJobType {
  PROSPECT = 'prospect',
  STRUCTURE = 'structure',
  VALIDATE = 'validate',
  ANGLES = 'angles',
  COPY = 'copy',
  RECYCLE = 'recycle',
}

export enum AIJobStatus {
  QUEUED = 'queued',
  RUNNING = 'running',
  SUCCEEDED = 'succeeded',
  FAILED = 'failed',
}
